# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 03 May 2012 21:11:21 +0000
blog:*	@ALL	1
blog:*	foozzi	8
main:*	@user	8
sandbox:*	@ALL	8
sandbox:*	@user	8
*	@user	8
start	@ALL	1
*	@ALL	1
debian:*	@user	8
ubuntu:*	@user	8
fedora:*	@user	8
wine:*	@user	8
best_autors	@user	1
about	@user	1
*	foozzi	16
